#!/usr/bin/env bash
# Generate .github/labeler.yml from repo layout (lives next to the output).
#
# Convention:
#   - each directory under src/cli/<area>/ → area:<area>
#   - kit modules explain / demos → area:explain, area:demos (path auto)
#   - product docs → docs (docs/**, README.md, demos markdown — not CONTRIBUTING)
#   - .github/** → ci
# No catch-all area:kit — shared paths are typed via type labels only.
#
# Usage:
#   ./.github/gen-labeler.sh           # write .github/labeler.yml
#   ./.github/gen-labeler.sh --check   # exit 1 if committed file is stale
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/.github/labeler.yml"

areas=()
for dir in "${ROOT}/src/cli"/*/; do
  [[ -d "$dir" ]] || continue
  name="$(basename "$dir")"
  [[ "$name" == _* ]] && continue
  areas+=("$name")
done
# Modules without src/cli/<area>/ — still first-class path areas.
areas+=(explain demos)

IFS=$'\n' areas_sorted=($(printf '%s\n' "${areas[@]:-}" | LC_ALL=C sort -u))
unset IFS

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  cat <<'EOF'
# AUTO-GENERATED by .github/gen-labeler.sh — do not edit by hand.
# Prefer directory / stem globs; regenerate after adding src/cli/<area>/.
# https://github.com/actions/labeler

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "README.md"
          - "demos/**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
EOF

  for area in "${areas_sorted[@]:-}"; do
    cat <<EOF

"area:${area}":
  - changed-files:
      - any-glob-to-any-file:
          - "src/DistSSHKit/${area}/**"
          - "src/DistSSHKit/${area}.*"
          - "src/cli/${area}/**"
          - "src/cli/${area}.*"
          - "test/**/${area}/**"
          - "test/**/${area}.*"
EOF
    # Bundled demos live under repo-root demos/ (not only DistSSHKit/demos.jl).
    if [[ "$area" == "demos" ]]; then
      cat <<'EOF'
          - "demos/**"
          - "test/integration/demos/**"
EOF
    fi
  done
} >"$tmp"

mkdir -p "$(dirname "$OUT")"

if [[ "${1:-}" == "--check" ]]; then
  if [[ ! -f "$OUT" ]]; then
    echo "missing $OUT — run ./.github/gen-labeler.sh" >&2
    exit 1
  fi
  if ! diff -u "$OUT" "$tmp" >&2; then
    echo "stale labeler.yml — run ./.github/gen-labeler.sh and commit" >&2
    exit 1
  fi
  echo "labeler.yml up to date"
  exit 0
fi

cp "$tmp" "$OUT"
echo "wrote $OUT (${#areas_sorted[@]} areas: ${areas_sorted[*]:-})"
