#!/usr/bin/env bash
# Generate .github/labeler.yml from repo layout (lives next to the output).
#
# Convention:
#   - each directory under src/cli/<area>/ → area:<area>
#   - shared kit paths → area:kit
#   - docs / markdown → docs
#   - .github/** → ci
# Manual-only (not generated): area:explain, area:demos — use for Issue triage;
# path changes under those surfaces are covered by area:kit.
#
# Usage:
#   ./.github/gen-labeler.sh           # write .github/labeler.yml
#   ./.github/gen-labeler.sh --check   # exit 1 if committed file is stale
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/.github/labeler.yml"

areas=()
for dir in "${ROOT}/src/cli"/*/; do
  [[ -d "$dir" ]] || continue
  name="$(basename "$dir")"
  [[ "$name" == _* ]] && continue
  areas+=("$name")
done

IFS=$'\n' areas_sorted=($(printf '%s\n' "${areas[@]:-}" | LC_ALL=C sort -u))
unset IFS

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  cat <<'EOF'
# AUTO-GENERATED by .github/gen-labeler.sh — do not edit by hand.
# Prefer directory / stem globs; regenerate after adding src/cli/<area>/.
# https://github.com/actions/labeler

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"
          - "demos/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
EOF

  for area in "${areas_sorted[@]:-}"; do
    cat <<EOF

"area:${area}":
  - changed-files:
      - any-glob-to-any-file:
          - "src/DistSSHKit/${area}/**"
          - "src/DistSSHKit/${area}.*"
          - "src/cli/${area}/**"
          - "src/cli/${area}.*"
          - "test/**/${area}/**"
          - "test/**/${area}.*"
EOF
  done

  cat <<'EOF'

# Shared kit surface (top-level modules, demos, harness). Area stems excluded below.
"area:kit":
  - changed-files:
      - any-glob-to-any-file:
          - "src/DistSSHKit/*"
          - "src/DistSSHKit/cli/**"
          - "demos/**"
          - "test/support/**"
          - "test/fixtures/**"
          - "test/artifacts/**"
          - "test/*"
          - "test/unit/DistSSHKit/cli/**"
          - "test/integration/demos/**"
          - "test/integration/ssh/**"
          - "testenv/**"
EOF

  for area in "${areas_sorted[@]:-}"; do
    printf '          - "!src/DistSSHKit/%s.*"\n' "$area"
  done
} >"$tmp"

mkdir -p "$(dirname "$OUT")"

if [[ "${1:-}" == "--check" ]]; then
  if [[ ! -f "$OUT" ]]; then
    echo "missing $OUT — run ./.github/gen-labeler.sh" >&2
    exit 1
  fi
  if ! diff -u "$OUT" "$tmp" >&2; then
    echo "stale labeler.yml — run ./.github/gen-labeler.sh and commit" >&2
    exit 1
  fi
  echo "labeler.yml up to date"
  exit 0
fi

cp "$tmp" "$OUT"
echo "wrote $OUT (${#areas_sorted[@]} areas: ${areas_sorted[*]:-})"
