name = "DistSSHKit"
uuid = "ceec0504-c968-4be5-b215-667cae0e8f81"
license = "MIT"
version = "0.9.0"
authors = ["Yamamoto, Takanori <takanori.yamamoto.99@gmail.com>", "Ampuku, Honoka <ampk.hono@gmail.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
DistSSHQueue = "24254401-70d8-4a51-8ea4-cfab19f5bc73"
DistSSHRun = "b568025c-2759-4ef1-8b14-17d00e2cd000"
DistSSHUp = "76a6745a-cbcc-444e-a19a-dcac12a79e7c"

[sources]
DistSSHQueue = {rev = "f89aa47eb5e0de660e5a7a74a696552c657ae991", url = "https://github.com/yamanori99/DistSSHQueue.jl"}
DistSSHRun = {rev = "1d02d092ab954b394394a0a3586ba1a27fb21e05", url = "https://github.com/yamanori99/DistSSHRun.jl"}
DistSSHUp = {rev = "01364eeab31539148dae853deaaf72bc5c46d1af", url = "https://github.com/yamanori99/DistSSHUp.jl"}

[compat]
DistSSHQueue = "0.8"
DistSSHRun = "0.1"
DistSSHUp = "0.1"
julia = "1.13"

[apps.distsshkit]
julia_flags = ["--startup-file=no"]
