# Shared helpers for real-SSH E2E (docker-ssh workers).

if !isdefined(Main, :_ssh_e2e_enabled)

using Dates

"""True when CI / local docker-ssh E2E should run."""
function _ssh_e2e_enabled()::Bool
    return get(ENV, "DISTSSHKIT_SSH_E2E", "") == "1"
end

"""Path to `testenv/docker-ssh` (repo-relative)."""
function _docker_ssh_root()::String
    return abspath(joinpath(_kit_root(), "testenv", "docker-ssh"))
end

"""SSH config / hosts file generated by `scripts/gen-keys.sh`."""
function _docker_ssh_generated()
    root = _docker_ssh_root()
    return (
        ssh_config=joinpath(root, ".generated", "ssh_config"),
        hosts_file=joinpath(root, ".generated", "hosts"),
        controller_key=joinpath(root, ".generated", "controller"),
    )
end

"""ENV overlay so DistSSHKit uses the docker-ssh SSH config (`-F`)."""
function _ssh_e2e_env(;
    remote_project::AbstractString,
    extra::Dict{String,String}=Dict{String,String}(),
)::Dict{String,String}
    g = _docker_ssh_generated()
    isfile(g.ssh_config) || error("missing $(g.ssh_config); run testenv/docker-ssh/scripts/up.sh")
    base = Dict{String,String}(
        "DISTSSHKIT_YES" => "1",
        "DISTSSHKIT_QUIET" => get(ENV, "DISTSSHKIT_QUIET", "1"),
        "DISTRIBUTED_SSH_OPTS" => "-F $(g.ssh_config)",
        "DISTRIBUTED_REMOTE_PROJECT_ROOT" => String(remote_project),
    )
    return merge(base, extra)
end

const _SSH_E2E_HOSTS = ("distsshkit-w1", "distsshkit-w2")
const _SSH_E2E_REMOTE_ROOT = "/home/dev/distsshkit-e2e"

"""Root for kept SSH E2E artifacts: `test/artifacts/ssh-e2e/` (gitignored)."""
function _ssh_e2e_artifact_root()::String
    return joinpath(_kit_root(), "test", "artifacts", "ssh-e2e")
end

"""
One SSH E2E invocation.

Open `SUMMARY.txt` first. Step captures live under `logs/`.
Temporary Julia projects used as `--project` live under `projects/`.
"""
mutable struct SshE2ESuite
    dir::String
    logs::String
    project_local::String
    project_remote::String
    step::Int
    rows::Vector{NTuple{4,String}}  # status, nn, name, rel_log
end

function _ssh_e2e_write_summary!(suite::SshE2ESuite)
    path = joinpath(suite.dir, "SUMMARY.txt")
    open(path, "w") do io
        println(io, "SSH E2E SUMMARY — open this first")
        println(io)
        println(io, "  ok/FAIL   step   name                        log file")
        println(io, "  ---------------------------------------------------------------")
        if isempty(suite.rows)
            println(io, "  (no steps yet)")
        else
            for (status, nn, name, rel) in suite.rows
                println(io, "  $(rpad(status, 4))     $(nn)     $(rpad(name, 28))  $(rel)")
            end
        end
        println(io)
        println(io, "Log header:  === NN  name  [ok|FAIL]  exit=N ===")
        println(io, "Suite: $(suite.dir)")
    end
    write(joinpath(_ssh_e2e_artifact_root(), "LATEST"), suite.dir * "\n")
    return path
end

"""
Create one artifact dir for the whole `run.jl` and call `f(suite)`.

  SUMMARY.txt
  logs/NN_name.log
  projects/local/
  projects/remote/
"""
function _with_ssh_e2e_suite(f::Function)
    root = _ssh_e2e_artifact_root()
    mkpath(root)
    stamp = Dates.format(Dates.now(Dates.UTC), "yyyymmddTHHMMSS") * "Z"
    dir = abspath(joinpath(root, "$(stamp)_suite"))
    logs = joinpath(dir, "logs")
    project_local = joinpath(dir, "projects", "local")
    project_remote = joinpath(dir, "projects", "remote")
    mkpath(logs)
    mkpath(project_local)
    mkpath(project_remote)
    suite = SshE2ESuite(dir, logs, project_local, project_remote, 0, NTuple{4,String}[])
    _ssh_e2e_write_summary!(suite)
    @info "SSH E2E artifacts" summary=joinpath(dir, "SUMMARY.txt")
    try
        return f(suite)
    finally
        _ssh_e2e_write_summary!(suite)
        @info "SSH E2E done — open SUMMARY.txt" joinpath(suite.dir, "SUMMARY.txt")
    end
end

"""Newest `*.log` under `dir`, or `nothing`."""
function _ssh_e2e_newest_log(dir::AbstractString)::Union{Nothing,String}
    isdir(dir) || return nothing
    files = filter(f -> endswith(lowercase(f), ".log") && isfile(f), readdir(dir; join=true))
    isempty(files) && return nothing
    return last(sort(files; by=mtime))
end

"""Save capture as `logs/NN_<slug>.log` and append a SUMMARY row.

When `project` + `kit` (`:setup` / `:go`) are set, prefer the kit log under
`project/.distsshkit/<kit>/` (full detail under quiet CLI) as the log body.
"""
function _ssh_e2e_record!(
    suite::SshE2ESuite,
    slug::AbstractString,
    proc,
    out::AbstractString;
    expect_ok::Bool=true,
    project::Union{Nothing,AbstractString}=nothing,
    kit::Union{Nothing,Symbol}=nothing,
)
    suite.step += 1
    nn = lpad(suite.step, 2, '0')
    safe = replace(String(slug), r"[^A-Za-z0-9._-]+" => "_")
    rel = "logs/$(nn)_$(safe).log"
    path = joinpath(suite.dir, rel)
    ok = expect_ok ? (proc.exitcode == 0) : (proc.exitcode != 0)
    status = ok ? "ok" : "FAIL"

    body = String(out)
    kit_src = nothing
    if project !== nothing && kit !== nothing
        newest = _ssh_e2e_newest_log(joinpath(project, ".distsshkit", String(kit)))
        if newest !== nothing
            kit_src = newest
            body = read(newest, String)
        end
    end

    # `let` so the `open` do-block does not box soft locals (JETLS).
    let body = body, kit_src = kit_src
        open(path, "w") do io
            println(io, "=== $(nn)  $(slug)  [$(status)]  exit=$(proc.exitcode) ===")
            kit_src !== nothing && println(io, "kit-log: $(kit_src)")
            println(io)
            print(io, body)
            endswith(body, "\n") || println(io)
        end
    end
    push!(suite.rows, (status, nn, String(slug), rel))
    _ssh_e2e_write_summary!(suite)
    return path
end

"""Record + `_assert_proc_ok` (expects exit 0)."""
function _assert_ssh_e2e_ok(
    suite::SshE2ESuite,
    slug::AbstractString,
    proc,
    out::AbstractString;
    project::Union{Nothing,AbstractString}=nothing,
    kit::Union{Nothing,Symbol}=nothing,
)
    _ssh_e2e_record!(suite, slug, proc, out; expect_ok=true, project=project, kit=kit)
    return _assert_proc_ok(proc, out; label=slug)
end

"""Init a minimal git repo in `proj` so setup --check can read a local hash."""
function _git_init_commit!(proj::AbstractString; message::AbstractString="e2e")
    run(pipeline(`git -C $proj init`; stdout=devnull, stderr=devnull))
    run(pipeline(`git -C $proj config user.email "e2e@distsshkit.test"`; stdout=devnull, stderr=devnull))
    run(pipeline(`git -C $proj config user.name "DistSSHKit E2E"`; stdout=devnull, stderr=devnull))
    run(pipeline(`git -C $proj add -A`; stdout=devnull, stderr=devnull))
    run(pipeline(`git -C $proj commit -m $message`; stdout=devnull, stderr=devnull))
    return nothing
end

"""Copy DistSSHKit `Project.toml` + `src/` into `proj/deps/DistSSHKit` (relative path dep)."""
function _vendor_distsshkit!(proj::AbstractString; kit_root::AbstractString=_kit_root())
    dest = joinpath(proj, "deps", "DistSSHKit")
    isdir(dest) && rm(dest; recursive=true)
    mkpath(dest)
    cp(joinpath(kit_root, "Project.toml"), joinpath(dest, "Project.toml"); force=true)
    cp(joinpath(kit_root, "src"), joinpath(dest, "src"); force=true)
    return dest
end

"""
Stage a durable SSH E2E remote project: vendored DistSSHKit, demos, smoke,
`Pkg.instantiate`, and a git commit (for setup --check).
"""
function _stage_ssh_e2e_remote_host!(
    proj::AbstractString;
    kit_root::AbstractString=_kit_root(),
    julia::AbstractString=_julia_exe(),
)
    proj = abspath(proj)
    _vendor_distsshkit!(proj; kit_root=kit_root)
    write(
        joinpath(proj, "Project.toml"),
        """
        name = "SshE2EApp"
        uuid = "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee"
        version = "0.0.1"

        [deps]
        DistSSHKit = "ceec0504-c968-4be5-b215-667cae0e8f81"
        Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

        [sources]
        DistSSHKit = {path = "deps/DistSSHKit"}
        """,
    )
    mkpath(joinpath(proj, "src"))
    write(joinpath(proj, "src", "SshE2EApp.jl"), "module SshE2EApp\nend\n")

    for (subdir, names) in (
        ("with_kit", ("square_echo.jl", "square_file.jl", "pipeline_square.jl")),
        ("without_kit", ("pi_echo.jl", "pi_file.jl")),
    )
        dest = joinpath(proj, "demos", subdir)
        mkpath(dest)
        for name in names
            src = joinpath(kit_root, "demos", subdir, name)
            isfile(src) || error("missing demo: $src")
            cp(src, joinpath(dest, name); force=true)
        end
    end
    cp(_fixture("drive_local_smoke.jl"), joinpath(proj, "smoke.jl"); force=true)

    inst = setenv(
        `$julia --startup-file=no --project=$proj -e "using Pkg; Pkg.instantiate()"`,
        _child_julia_env(),
    )
    proc, out = _run_subprocess(inst)
    _assert_proc_ok(proc, out; label="ssh-e2e Pkg.instantiate")

    _git_init_commit!(proj)
    return nothing
end

"""Newest go batch dir under `proj/.distsshkit/go/`, or `nothing`."""
function _ssh_e2e_latest_go_batch(proj::AbstractString)::Union{Nothing,String}
    root = joinpath(proj, ".distsshkit", "go")
    isdir(root) || return nothing
    batches = filter(isdir, readdir(root; join=true))
    isempty(batches) && return nothing
    return last(sort(batches; by=mtime))
end

end
