# Runner CLI: kit-internal names in `Main` (see `drive.jl`).
using .DistSSHKit:
    LOG_FILE_HANDLE,
    close_log_file,
    collect_tree_remote_files_ssh,
    detect_julia_path,
    display_path,
    dist_ssh_kit_version,
    distributed_collect_root_dirs,
    get_local_git_hash,
    init_log_file,
    julia_env_record,
    kit_progress_begin!,
    kit_progress_done!,
    kit_progress_step!,
    local_git_clean,
    print_err,
    print_header,
    print_help_blank,
    print_help_chrome,
    print_help_lines,
    print_help_section,
    print_info,
    print_ok,
    print_progress_err,
    print_progress_warn,
    println_fatal,
    project_package_name,
    remote_path_for_ssh_collect,
    resolve_host_path_abs,
    resolve_pkg_project_dir,
    ssh_opts,
    subcommand_args_record,
    write_both,
    writeln_both,
    writeln_field

include(joinpath(@__DIR__, "..", "_common.jl"))
